"""
test_timeseries_output.py
Unit tests confirming that run_backtest() and gate1_reporter produce
equity_curve and trade_log fields with correct JSON schema.

Run with:
    cd orchestrator
    python -m pytest tests/test_timeseries_output.py -v
"""

import json
import sys
from pathlib import Path

import pandas as pd
import numpy as np
import pytest

# Add orchestrator to path
sys.path.insert(0, str(Path(__file__).parent.parent))

from quant_orchestrator import run_backtest
from gate1_reporter import generate_and_save_verdict, _BACKTESTS_TEST_DIR


# ── Helpers ───────────────────────────────────────────────────

def _make_data(n: int = 252, seed: int = 0) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    close = 100 * np.cumprod(1 + rng.normal(0.0005, 0.01, n))
    idx = pd.date_range("2020-01-02", periods=n, freq="B")
    return pd.DataFrame({
        "Open": close * 0.99,
        "High": close * 1.01,
        "Low": close * 0.98,
        "Close": close,
        "Volume": rng.integers(1_000_000, 5_000_000, n),
    }, index=idx)


# Simple mean-reversion strategy that produces a few trades
_SIMPLE_STRATEGY = """
import vectorbt as vbt
import pandas as pd

close = data["Close"]
ma = close.rolling(20).mean()
entries = close < ma * 0.98
exits = close > ma
portfolio = vbt.Portfolio.from_signals(close, entries, exits, init_cash=100_000, freq='D')
"""


# ── run_backtest output schema ────────────────────────────────

def test_run_backtest_returns_equity_curve():
    data = _make_data()
    result = run_backtest(_SIMPLE_STRATEGY, data, asset_class="equities")
    assert "equity_curve" in result, "run_backtest must return 'equity_curve'"
    ec = result["equity_curve"]
    assert isinstance(ec, list), "equity_curve must be a list"
    assert len(ec) > 0, "equity_curve must be non-empty"


def test_equity_curve_record_schema():
    data = _make_data()
    result = run_backtest(_SIMPLE_STRATEGY, data, asset_class="equities")
    ec = result["equity_curve"]
    required_keys = {"date", "portfolio_value", "drawdown_pct"}
    for record in ec:
        assert required_keys <= record.keys(), f"equity_curve record missing keys: {required_keys - record.keys()}"
        # date must be a 10-char YYYY-MM-DD string
        assert len(record["date"]) == 10 and record["date"][4] == "-", f"bad date format: {record['date']}"
        assert isinstance(record["portfolio_value"], float), "portfolio_value must be float"
        assert isinstance(record["drawdown_pct"], float), "drawdown_pct must be float"


def test_run_backtest_returns_trade_log():
    data = _make_data()
    result = run_backtest(_SIMPLE_STRATEGY, data, asset_class="equities")
    assert "trade_log" in result, "run_backtest must return 'trade_log'"
    assert isinstance(result["trade_log"], list), "trade_log must be a list"


def test_trade_log_record_schema():
    data = _make_data()
    result = run_backtest(_SIMPLE_STRATEGY, data, asset_class="equities")
    trade_log = result["trade_log"]
    if not trade_log:
        pytest.skip("No trades generated by strategy — schema check skipped")
    required_keys = {"trade_id", "entry_date", "exit_date", "entry_price", "exit_price",
                     "shares", "direction", "pnl", "pnl_pct"}
    for record in trade_log:
        assert required_keys <= record.keys(), f"trade_log record missing keys: {required_keys - record.keys()}"
        assert record["direction"] in ("long", "short"), f"direction must be 'long' or 'short'"
        assert isinstance(record["pnl"], float), "pnl must be float"
        assert isinstance(record["pnl_pct"], float), "pnl_pct must be float"


# ── gate1_reporter JSON output schema ─────────────────────────

def _make_pass_metrics(is_ec, oos_ec, is_tl, oos_tl):
    return {
        "sharpe_in_sample": 1.5,
        "sharpe_out_of_sample": 1.1,
        "max_dd_in_sample": 0.12,
        "max_dd_out_of_sample": 0.15,
        "win_rate_in_sample": 0.55,
        "trades_in_sample": 200,
        "dsr_zscore": 1.8,
        "wf_windows": [
            {"train_sharpe": 1.4, "test_sharpe": 1.1},
            {"train_sharpe": 1.6, "test_sharpe": 1.2},
            {"train_sharpe": 1.5, "test_sharpe": 1.0},
            {"train_sharpe": 1.3, "test_sharpe": 1.05},
        ],
        "param_sensitivity_passed": True,
        "param_sensitivity_max_delta": 0.12,
        "post_cost_sharpe_oos": 0.95,
        "n_trials": 5,
        "equity_curve_is": is_ec,
        "equity_curve_oos": oos_ec,
        "trade_log_is": is_tl,
        "trade_log_oos": oos_tl,
    }


def test_gate1_reporter_json_has_equity_curve_and_trade_log():
    data = _make_data()
    result = run_backtest(_SIMPLE_STRATEGY, data, asset_class="equities")
    ec = result["equity_curve"]
    tl = result["trade_log"]

    metrics = _make_pass_metrics(ec[:len(ec)//2], ec[len(ec)//2:], tl, [])
    proposal = {"strategy_name": "TestTimeSeries"}
    config = {"in_sample_start": "2020-01-02", "out_of_sample_end": "2020-12-31"}

    verdict = generate_and_save_verdict(metrics, proposal, config, output_dir=_BACKTESTS_TEST_DIR)

    json_path = Path(verdict["json_path"])
    assert json_path.exists(), "Gate 1 JSON file must be created"

    saved = json.loads(json_path.read_text())
    assert "equity_curve" in saved, "JSON must contain 'equity_curve'"
    assert "trade_log" in saved, "JSON must contain 'trade_log'"
    assert isinstance(saved["equity_curve"], list), "equity_curve must be a list"
    assert isinstance(saved["trade_log"], list), "trade_log must be a list"
    assert len(saved["equity_curve"]) == len(ec), "equity_curve length must equal IS + OOS combined"


def test_gate1_reporter_json_empty_series_when_no_trades():
    """Strategies with no trades should still produce empty list fields, not missing keys."""
    metrics = _make_pass_metrics([], [], [], [])
    proposal = {"strategy_name": "NoTradesStrat"}
    config = {"in_sample_start": "2020-01-02", "out_of_sample_end": "2020-12-31"}

    verdict = generate_and_save_verdict(metrics, proposal, config, output_dir=_BACKTESTS_TEST_DIR)
    saved = json.loads(Path(verdict["json_path"]).read_text())

    assert "equity_curve" in saved
    assert "trade_log" in saved
    assert saved["equity_curve"] == []
    assert saved["trade_log"] == []
